common: &default_settings
  license_key: <%= NEW_RELIC_LICENSE_KEY %>
  app_name: TMC
  log_level: info


development:
  <<: *default_settings
  app_name: TMC (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: TMC (Staging)

production:
  <<: *default_settings
